{% set name = "microtc" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microtc-{{ version }}.tar.gz
  sha256: 96c602908fe78ee7b75ce66ed1b4b5eba7cd9dd77b1b8eccbd7e3a046dffb655

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - scikit-learn
    - python
    - pip
  run:
    - python
    - scikit-learn

test:
  imports:
    - microtc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/microtc/
  summary: A generic minimal text classifier
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
