{% set name = "microtc" %}
{% set version = "2.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microtc-{{ version }}.tar.gz
  sha256: cb5db421deee70ecc0ed335896228b13d156f5939a0022559aa43d316fab0ed4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - scikit-learn
    - python
    - pip
  run:
    - python
    - scikit-learn

test:
  imports:
    - microtc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/microtc/
  summary: A generic minimal text classifier
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
