{% set name = "microtc" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microtc-{{ version }}.tar.gz
  sha256: 8190825a40491152e4143738bc19d315ff7f6a3b70eeb1c5f3314c8c7fd6a26b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - scikit-learn
    - python
    - pip
  run:
    - python
    - scikit-learn

test:
  imports:
    - microtc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/microtc/
  summary: A generic minimal text classifier
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
