{% set name = "microtc" %}
{% set version = "2.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microtc-{{ version }}.tar.gz
  sha256: 232a19f4d7377ff29d93d9b146d06a9a3f5f57d7b67a04b2dc617179e966e6e2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - scikit-learn
    - python
    - pip
  run:
    - python
    - scikit-learn

test:
  imports:
    - microtc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/microtc/
  summary: A generic minimal text classifier
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
