{% set name = "microtc" %}
{% set version = "2.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microtc-{{ version }}.tar.gz
  sha256: 0fdffc32126c1cd81ac29fa8f73665b674b98d468cb2d9cd1fc65b692409d9e2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - scikit-learn
    - python
    - pip
  run:
    - python
    - scikit-learn

test:
  imports:
    - microtc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/microtc/
  summary: A generic minimal text classifier
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
